### ISSUE TITLE
GPU memory needed

### ISSUE THREAD

**Issue by primecai** [sxyu/pixel-nerf#24]
Hello,

I'm wondering how much GPU memory is needed? I'm using an RTX2080Ti with 11Gb memory but keep getting CUDA out of memory error even if I add "-R 100" flag(for DTU experiments).

Many thanks.

**Comment by danperazzo** [comment]
Hello @HexagonPrime, I have the exact same configuration as yours. I decreased the batch size to 2 instead of 4 and it is now training in the DTU dataset

**Comment by primecai** [comment]
Many thanks for the reply. Did you change any other configuration upon the defaults? And I'm wondering what CUDA&pytorch version are you using?

**Comment by danperazzo** [comment]
I did not change any other setting and I am using pytorch 1.7.1 and CUDA 9.2.

**Comment by amughrabi** [comment]
For the training: It worked like a charm when I changed `-V` to `2`.
